
#ifndef __COMMANDCODE_H__
#define __COMMANDCODE_H__

typedef enum {
    CMD_SIGNIN = 0,
    CMD_LOGIN = 1,
    CMD_SEND_MESSAGE_TO_CHATROOM = 2,
    CMD_CREATE_ROOM = 3,
    CMD_JOIN_ROOM = 4,
    CMD_VIEW_ONLINE_USERS = 5,
    CMD_INVITE_TO_ROOM = 6,
    CMD_RESPONSE_INVITATION = 7,
    CMD_VIEW_ROOM_USERS = 8,
    CMD_REMOVE_MEMBER = 9,
    CMD_LEAVE_ROOM = 10,
    CMD_VIEW_ROOMS = 11,
    CMD_SEND_FRIEND_REQUEST = 12,
    CMD_RESPONSE_FRIEND_REQUEST = 13,
    CMD_VIEW_FRIEND_REQUEST = 14,
    CMD_VIEW_FRIEND_LIST = 15,
    CMD_UNFRIEND = 16,
    CMD_VIEW_ONLINE_FRIENDS = 17,
    CMD_REQUEST_PRIVATE_MESSAGE = 18,
    CMD_RESPONSE_CHAT_REQUEST = 19,
    CMD_DISCONNECT_CHAT = 20,
    CMD_SEND_PRIVATE_MESSAGE = 21,
} CommandCode;

#endif // __COMMANDCODE_H__